Packer base
Otus-DevOps-2022-11/dmitry-sviridov_infra pull request #4
Opened 2023-01-06 17:16 UTC by dmitry-sviridov

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 -

## Как проверить работоспособность:
 - Например, перейти по ссылке http://130.193.43.218:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-07 08:39 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно внести небольшие правки
ДЗ возвращаю на доработку

2023-01-07 08:39 UTC, mrgreyves commented on packer/variables.json.examples
> +{
Стоит переименовать в variables.json.example

2023-01-12 15:27 UTC, dmitry-sviridov commented on packer/variables.json.examples
> +{
переименовал

2023-01-14 14:01 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все классно
ДЗ принимаю =)

2023-01-16 08:37 UTC, merged